from . import inherit_hr_employee
from . import inherit_hr_payslip
from . import inherit_hr_payslip_run
from . import inherit_hr_payslip_employees
from . import libro_sueldos
from . import inherit_hr_salary_rule
from . import inherit_hr_payroll_structure
from . import inherit_hr_contract
from . import vacaciones
from . import inherit_res_company
from . import hr_employee_libro